### ISSUE TITLE
buildout > grocery item detail modal

### ISSUE THREAD

**Issue by ryanschaefer41** [vigetlabs/EcoCart#12]
### Resources

- [Wireframes](https://whimsical.com/DhfTKr3NJ8VA1NBTGRRMNq)
- [Functionality](https://docs.google.com/document/d/1U1ka9nz5bAwlqXalyVK1fCL3Bx4RVLNK15Txv_ryW88/edit)

Probably makes sense to address the top half layout first and then turn toward the data viz stuff when the library is set up and data is finalized.

**Comment by doylejack74** [comment]
#57
