### ISSUE TITLE
enhancement>pie chart data viz>impact area descriptions missing and no %'s

### ISSUE THREAD

**Issue by doylejack74** [vigetlabs/EcoCart#42]
**There are no descriptions under the 4 impact areas next to the pie chart**
As of now, there are word fillers for the descriptions under the 4 impact areas next to the pie chart. This can lead to confusion and any possible ambiguity of our data.

**Replace filler descriptions with definitions of each impact area and include percentages of pie-chart makeup next to the chart**
To replace the filler words, you can add definitions of each impact area. Examples are:
- Carbon Emissions: Carbon emissions account for <<(x%)>> of your total Environmental Impact based on the amount of Green House Gas(GHG) emissions emitted from the supply chain of food production. The Supply Chain consists of Land Use Change, Farming, Animal Feed, Processing, Transportation, Retail, and Packaging. 
- Land Use: Land Use accounts for <<(x%)>> of your total Environmental Impact based on the amount of land used in food production. 
- Water Use: Water Use accounts for <<(x%)>> of your total Environmental Impact based on the number of freshwater withdrawals used in food production.
- Eutrophication: Eutrophication accounts for <<(x%)>> of your total Environmental Impact based on the amount of water pollution and chemical runoff that contribute to food production.

**Alternatives**
If this process consists of too much manual data entry, I think it would also be possible to just delete the filler descriptions and only include the titles. Regardless, I think the percentage #'s should be present somewhere in the visualization. 

**Additional Context**
![image](https://user-images.githubusercontent.com/66963476/88935769-17fe9b80-d250-11ea-89e0-6f8e4a34f2c1.png)

**Comment by willyd332** [comment]
I will also do a similar fix to the item modal descriptions
