### ISSUE TITLE
Consistent Font Family for all Headings

### ISSUE THREAD

**Issue by MikaByar34** [vigetlabs/EcoCart#43]
**Is your feature request related to a problem? Please describe.**
The "EcoCart" heading text seems like it may be a different font family than the rest of the headings on the site. 

**Describe the solution you'd like**
I think it might look nice if we changed the "EcoCart" heading's font to the same family as the other headings on the site. It can be restyled by changing the weight to give it more emphasis. 

**Describe alternatives you've considered**

**Additional context**
<img width="717" alt="ecocart-heading" src="https://user-images.githubusercontent.com/67015239/88945484-0ae7a980-d25c-11ea-8ec9-cd568636f354.png">

<img width="703" alt="Screen Shot 2020-07-30 at 12 00 21 PM" src="https://user-images.githubusercontent.com/67015239/88945771-66b23280-d25c-11ea-9474-da87cb7388d0.png">

**Comment by willyd332** [comment]
Done
