### ISSUE TITLE
Button Colors

### ISSUE THREAD

**Issue by MikaByar34** [vigetlabs/EcoCart#44]
**Is your feature request related to a problem? Please describe.**
Match button colors to button colors from comp. Comp colors will fit consistently with the theme and describe button actions well. 

**Describe the solution you'd like**
 Forward/add/positive action buttons = Green (Hex #: 16B545)
 Remove/delete items/negative action buttons = Red (Hex #: B00020)

**Describe alternatives you've considered**

**Additional context**
<img width="152" alt="Screen Shot 2020-07-30 at 12 49 16 PM" src="https://user-images.githubusercontent.com/67015239/88951176-a6c8e380-d263-11ea-828c-2fb469d39468.png">
<img width="291" alt="Screen Shot 2020-07-30 at 12 53 34 PM" src="https://user-images.githubusercontent.com/67015239/88951235-b5af9600-d263-11ea-87b1-933635f4858b.png">

**Comment by willyd332** [comment]
What colors should the button in the Cart modal be? currently they are that Orange/Blue combo.

**Comment by MikaByar34** [comment]
I would say the checkout/view impact button should definitely be green. I'm not as sure for the "Add Items" button. I think that one should maybe be green too.

**Comment by willyd332** [comment]
Done
