### ISSUE TITLE
Make Hero Text Unscrollable

### ISSUE THREAD

**Issue by MikaByar34** [vigetlabs/EcoCart#45]
**Is your feature request related to a problem? Please describe.**
Scrolling through the hero text box can be a bit of a hassle. On mobile it becomes a bigger problem since the side margins are incredibly thin and make it hard to scroll down the page. 

**Describe the solution you'd like**
Make the hero text container static instead of scrollable. 

**Describe alternatives you've considered**
Increase side margins on mobile. 

**Additional context**
<img width="268" alt="Screen Shot 2020-07-30 at 11 18 14 AM" src="https://user-images.githubusercontent.com/67015239/88951899-9feea080-d264-11ea-8fad-63d40e3d7b48.png">

**Comment by willyd332** [comment]
Done
