### ISSUE TITLE
Nav Bar Issues on Samsung Galaxy S20

### ISSUE THREAD

**Issue by MikaByar34** [vigetlabs/EcoCart#46]
**Describe the bug**
List icon in nav bar gets cut off on the top right corner of the screen. 

**To Reproduce**
1. Go to 'ecocart.app'
2. Scroll to show Nav bar
3. See error

**Expected behavior**
All elements should fully show up in the nav bar with even spacing. 

**Screenshots**
<img width="288" alt="Screen Shot 2020-07-30 at 11 18 28 AM" src="https://user-images.githubusercontent.com/67015239/88953304-b990e780-d266-11ea-83ee-328e822f0798.png">

**Mobile (please complete the following information):**
 - Device: [Samsung Galaxy S20]
 - OS: [Android]
 - Browser [Chrome]

**Comment by willyd332** [comment]
Done
