### ISSUE TITLE
EcoCart Logo In Nav Bar Appears Small on Ipad 

### ISSUE THREAD

**Issue by MikaByar34** [vigetlabs/EcoCart#47]
**Is your feature request related to a problem? Please describe.**
The Logo contained within the nav bar appears to be very small when viewing on an Ipad screen

**Describe the solution you'd like**
Increase the size of the logo for Ipad viewport

**Describe alternatives you've considered**
It's not a huge issue so It could be left alone if it's too much of a hassle. 

**Additional context**
<img width="164" alt="Screen Shot 2020-07-30 at 11 25 28 AM" src="https://user-images.githubusercontent.com/67015239/88953745-5ce1fc80-d267-11ea-98ff-026d8701c680.png">

**Comment by willyd332** [comment]
done
