### ISSUE TITLE
Enhancement > Homepage > Into text scroll feature 

### ISSUE THREAD

**Issue by Jennymontoya** [vigetlabs/EcoCart#51]
**Is your feature request related to a problem? Please describe.**
Users have the ability to scroll through the intro text under the heading "ECOCART". The scroll feature is a bit awkward across all devices. I has a strange appearance on Windows 10 Chrome, in particular. 

**Describe the solution you'd like**
Remove text scroll feature.

**Describe alternatives you've considered**
The text will be short, so there shouldn't really be a need for scrolling in the first place. Technically we can keep it there, but if it's possible to get rid of it then we should do so. 

**Additional context**
![Text Scroll](https://user-images.githubusercontent.com/66967309/88965938-84da5b80-d279-11ea-9b76-1c227cc86119.png)

**Comment by willyd332** [comment]
This has already been removed, I don't know why it is showing up on your end. Maybe try clearing your cache?
