### ISSUE TITLE
bug > landing page > navigation bar cut in half in horizontal orientation on mobile devices

### ISSUE THREAD

**Issue by doylejack74** [vigetlabs/EcoCart#58]
**The Navigation Bar is formatted wrong in horizontal orientation on all mobile devices**
On Android devices, the navigation bar isn't formatted wider than the logo, "Welcome", "Groceries", and Checkout Modal. It looks almost perfect on iOs devices, but the logo is still slightly bigger than the navigation bar. 

**To Reproduce**
Steps to reproduce the behavior ON MOBILE:
1. Go to ecocart.app
2. Turn device to horizontal lock
3. See error in the navigation bar

**Expected behavior**
The navigation bar should format over the action items and not in the middle of the items.

**Screenshots**
![image](https://user-images.githubusercontent.com/66963476/89068778-f11f9280-d33f-11ea-8733-ff6e06f30b7d.png)![image](https://user-images.githubusercontent.com/66963476/89068771-ee24a200-d33f-11ea-8ac4-ccdeeeb024f6.png)

**Mobile (please complete the following information):**
 - Device: iPhone 11
 - OS: iOS 13.6
 - Browser: Safari

**Mobile**
 - Device: Samsung Galaxy S20
 - OS: Android
 - Browser: Chrome

**Mobile**
 - Device: Google Pixel 4
 - Browser: Chrome

**Comment by willyd332** [comment]
This should have been already fixed. Can you try to recreate it again?
