### ISSUE TITLE
bug > impact receipt > hover for grading info does not work on mobile and iPad devices

### ISSUE THREAD

**Issue by doylejack74** [vigetlabs/EcoCart#60]
**The Hover option for more grading information only works on Mac for Safari and Chrome**
When you hover over the icon in the top right corner of the receipt, no information pops up on the iPad and mobile devices.

**To Reproduce**
1. Go to ecocart.app
2. Scroll to groceries section
3. Add items to your cart
4. Open checkout modal
5. Click "View Impact"
6. Move cursor over the icon in the top right corner and see error(nothing).

**Expected behavior**
The grading information should appear when you hover your cursor over the icon.

**Mobile:**
 - Device: iPhone 11
 - OS: iOs 13.6
 - Browser Safari

**iPad:**
 - Device: iPad Pro
 - OS: iOs 13.6
 - Browser: Safari 2020
 - Version 12.9

**Mobile:**
 - Device: Samsung Galaxy S20
 - OS: Android
 - Browser: Chrome

**Mobile:**
 - Device: Google Pixel 4
 - OS: Android
 - Browser: Chrome

**Comment by nellbhealy** [comment]
Since mobile use is driven by press events (e.g. tapping on the phone), that means hovering isn't something that's possible on mobile. So by default the icon shows the information on a longpress, but I did go ahead and change that to show on a regular press.
