### ISSUE TITLE
bug > impact receipt > No descriptions for impact breakdown areas on mobile devices and iPad and different formatting

### ISSUE THREAD

**Issue by doylejack74** [vigetlabs/EcoCart#61]
**Missing impact area descriptions on mobile and iPad**
The impact breakdown area at the bottom of the receipt shows the impact area descriptions on MAC, but not on any other devices (mobile & iPad). 
![image](https://user-images.githubusercontent.com/66963476/89079725-1d91d980-d355-11ea-8fd0-12663f7ae700.png)

**Incorrect formatting of impact areas at the bottom of the receipt page on mobile devices and iPad in Vertical orientation.**
iPad Pro
![image](https://user-images.githubusercontent.com/66963476/89079624-e1f70f80-d354-11ea-8b95-a5e7fe723e45.png)
Samsung Galaxy S20
![image](https://user-images.githubusercontent.com/66963476/89079637-e91e1d80-d354-11ea-9fb9-0f7338cf0630.png)
Samsung Galaxy S20
![image](https://user-images.githubusercontent.com/66963476/89079681-0652ec00-d355-11ea-9499-01bda335ef89.png)

**To Reproduce**
1. Go to receipt page on mobile devices and iPad in Vertical orientation.
2. Scroll down to the bottom of the page and see error.

**Expected behavior**
There should be descriptions next to the impact areas and text should be formatted to match the comps.

**Mobile:**
 - Device: iPhone 11
 - OS: iOs 13.6
 - Browser Safari

**iPad:**
 - Device: iPad Pro
 - OS: iOs 13.6
 - Browser: Safari 2020
 - Version 12.9

**Mobile:**
 - Device: Samsung Galaxy S20
 - OS: Android
 - Browser: Chrome

**Mobile:**
 - Device: Google Pixel 4
 - OS: Android
 - Browser: Chrome

**Comment by nellbhealy** [comment]
Are the timestamps in these correct? 
If so, the last two photos are outdated, and I did fix those bugs.
If not, darn I thought I fixed that.

Also, for the first image: that is the intended behavior for small screens. We can change that if needed, let's discuss with the group!
